---
- name: Verify deployment
  hosts: all
  gather_facts: false

  tasks:
    # =========================================================================
    # Service Health Checks
    # =========================================================================
    - name: Check MCP server health
      ansible.builtin.uri:
        url: http://localhost:3100/health
        return_content: true
      register: health
      failed_when: "'ok' not in health.content"

    - name: Check tmux-control-plane service is enabled
      ansible.builtin.command: systemctl --user is-enabled tmux-control-plane
      register: tmux_cp_enabled
      changed_when: false
      failed_when: tmux_cp_enabled.stdout != 'enabled'

    - name: Check tmux-control-plane service is running
      ansible.builtin.command: systemctl --user is-active tmux-control-plane
      register: tmux_cp_active
      changed_when: false
      failed_when: tmux_cp_active.stdout != 'active'

    - name: Check claude-tmux service is enabled
      ansible.builtin.command: systemctl --user is-enabled claude-tmux
      register: claude_tmux_enabled
      changed_when: false
      failed_when: claude_tmux_enabled.stdout != 'enabled'

    - name: Check claude-tmux service is running
      ansible.builtin.command: systemctl --user is-active claude-tmux
      register: claude_tmux_active
      changed_when: false
      failed_when: claude_tmux_active.stdout != 'active'

    # =========================================================================
    # GitHub MCP Service (conditional - only if vault_github_pat is set)
    # =========================================================================
    - name: Check if github-mcp service exists
      ansible.builtin.command: systemctl --user list-unit-files github-mcp.service
      register: github_mcp_exists
      changed_when: false
      failed_when: false

    - name: Check github-mcp service is enabled
      ansible.builtin.command: systemctl --user is-enabled github-mcp
      register: github_mcp_enabled
      changed_when: false
      failed_when: github_mcp_enabled.stdout != 'enabled'
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp service is running
      ansible.builtin.command: systemctl --user is-active github-mcp
      register: github_mcp_active
      changed_when: false
      failed_when: github_mcp_active.stdout != 'active'
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp env file exists with secure permissions
      ansible.builtin.stat:
        path: ~/.config/github-mcp/env
      register: github_mcp_env
      failed_when: >-
        github_mcp_env.stat.exists and
        github_mcp_env.stat.mode != '0600'
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp start script exists
      ansible.builtin.stat:
        path: ~/github-mcp/start.sh
      register: github_mcp_script
      failed_when: >-
        'github-mcp.service' in github_mcp_exists.stdout and
        not github_mcp_script.stat.exists
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp healthcheck script exists
      ansible.builtin.stat:
        path: ~/github-mcp/healthcheck.sh
      register: github_mcp_healthcheck
      failed_when: >-
        'github-mcp.service' in github_mcp_exists.stdout and
        not github_mcp_healthcheck.stat.exists
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp-watchdog timer is enabled
      ansible.builtin.command: systemctl --user is-enabled github-mcp-watchdog.timer
      register: watchdog_timer_enabled
      changed_when: false
      failed_when: watchdog_timer_enabled.stdout != 'enabled'
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check github-mcp-watchdog timer is active
      ansible.builtin.command: systemctl --user is-active github-mcp-watchdog.timer
      register: watchdog_timer_active
      changed_when: false
      failed_when: watchdog_timer_active.stdout != 'active'
      when: "'github-mcp.service' in github_mcp_exists.stdout"

    - name: Check tmux session exists
      ansible.builtin.command: tmux has-session -t main
      register: tmux_session
      changed_when: false
      failed_when: tmux_session.rc != 0

    # =========================================================================
    # Service Restart Tests (verifies handlers work correctly)
    # =========================================================================
    - name: Test tmux-control-plane can restart
      ansible.builtin.systemd:
        name: tmux-control-plane
        state: restarted
        scope: user

    - name: Wait for MCP server to be ready after restart
      ansible.builtin.uri:
        url: http://localhost:3100/health
        return_content: true
      register: health_after_restart
      until: "'ok' in health_after_restart.content"
      retries: 10
      delay: 2

    - name: Test claude-tmux can restart
      ansible.builtin.systemd:
        name: claude-tmux
        state: restarted
        scope: user

    - name: Wait for tmux session after restart
      ansible.builtin.command: tmux has-session -t main
      register: tmux_after_restart
      until: tmux_after_restart.rc == 0
      retries: 10
      delay: 2
      changed_when: false

    # =========================================================================
    # Docker Checks
    # =========================================================================
    - name: Check Docker is installed
      ansible.builtin.command: docker --version
      register: docker_version
      changed_when: false
      failed_when: docker_version.rc != 0

    - name: Check user is in docker group
      ansible.builtin.command: groups
      register: user_groups
      changed_when: false
      failed_when: "'docker' not in user_groups.stdout"

    - name: Check Docker image exists
      ansible.builtin.command: docker images claude-code --format "{{ '{{' }}.Repository{{ '}}' }}"
      register: docker_image
      changed_when: false
      failed_when: "'claude-code' not in docker_image.stdout"

    # =========================================================================
    # Node.js / Tool Checks
    # =========================================================================
    - name: Check nvm is installed
      ansible.builtin.stat:
        path: ~/.nvm/nvm.sh
      register: nvm_check
      failed_when: not nvm_check.stat.exists

    - name: Check Node.js is available
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh
        node --version
      args:
        executable: /bin/bash
      register: node_version
      changed_when: false
      failed_when: node_version.rc != 0

    - name: Check pnpm is available
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh
        pnpm --version
      args:
        executable: /bin/bash
      register: pnpm_version
      changed_when: false
      failed_when: pnpm_version.rc != 0

    # =========================================================================
    # Playwright / Browser Checks
    # =========================================================================
    - name: Check Playwright is installed in Docker image
      ansible.builtin.command: docker run --rm claude-code npx playwright --version
      register: playwright_version
      changed_when: false
      failed_when: playwright_version.rc != 0

    - name: Check Chromium browser is available
      ansible.builtin.command: docker run --rm claude-code npx playwright install --dry-run chromium
      register: chromium_check
      changed_when: false
      failed_when: "'chromium' not in chromium_check.stdout"

    # =========================================================================
    # File and Directory Checks
    # =========================================================================
    - name: Check SSH key was generated
      ansible.builtin.stat:
        path: ~/.claude-docker/.ssh/id_ed25519
      register: ssh_key
      failed_when: not ssh_key.stat.exists

    - name: Check claude-sandbox.sh is executable
      ansible.builtin.stat:
        path: ~/claude-sandbox.sh
      register: sandbox_script
      failed_when: not sandbox_script.stat.executable

    - name: Check claude-attach.sh is executable
      ansible.builtin.stat:
        path: ~/claude-attach.sh
      register: attach_script
      failed_when: not attach_script.stat.executable

    - name: Check required directories exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: dir_check
      loop:
        - ~/Sessions
        - ~/.claude-docker
        - ~/.claude-docker/.ssh
        - ~/.claude-control-plane
        - ~/.claude-control-plane/workspace
        - ~/tmux-control-plane
        - ~/claude-sandbox-image
      failed_when: not dir_check.stat.exists

    - name: Check MCP server files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: mcp_files
      loop:
        - ~/tmux-control-plane/server.js
        - ~/tmux-control-plane/package.json
        - ~/tmux-control-plane/start.sh
        - ~/tmux-control-plane/node_modules
      failed_when: not mcp_files.stat.exists

    - name: Check config files exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: config_files
      loop:
        - ~/.tmux.conf
        - ~/.claude-docker/settings.json
        - ~/.claude-docker/.ssh/config
        - ~/.claude-control-plane/workspace/.mcp.json
      failed_when: not config_files.stat.exists

    # =========================================================================
    # OAuth Token Checks
    # =========================================================================
    - name: Check Claude OAuth credentials exist
      ansible.builtin.stat:
        path: ~/.claude-docker/.credentials.json
      register: claude_creds
      failed_when: not claude_creds.stat.exists

    - name: Check Happy Coder tokens (optional)
      ansible.builtin.stat:
        path: ~/.claude-docker/.happy/access.key
      register: happy_creds
      failed_when: false  # Optional

    # =========================================================================
    # Optional Components
    # =========================================================================
    - name: Verify Tailscale is installed
      ansible.builtin.command: which tailscale
      register: tailscale_check
      changed_when: false
      failed_when: false  # Optional - don't fail if not installed

    - name: Check Claude Code on host (optional)
      ansible.builtin.shell: |
        source ~/.nvm/nvm.sh
        which claude || true
      args:
        executable: /bin/bash
      register: claude_host
      changed_when: false
      failed_when: false

    # =========================================================================
    # MCP Session Spawn Tests
    # =========================================================================
    - name: Load vault variables for MCP token
      ansible.builtin.include_vars:
        file: ../../group_vars/all/vault.yml

    - name: Spawn session via MCP with repo and session name
      ansible.builtin.uri:
        url: http://localhost:3100/mcp
        method: POST
        headers:
          Authorization: "Bearer {{ vault_mcp_bearer_token }}"
          Content-Type: application/json
        body_format: json
        body:
          jsonrpc: "2.0"
          id: 1
          method: tools/call
          params:
            name: spawn_session
            arguments:
              repo: "github.com/test/my-repo"
              session_name: "Test Session"
        return_content: true
      register: spawn_result

    - name: Verify session directory created with correct path
      ansible.builtin.find:
        paths: ~/Sessions
        patterns: "my-repo--test-session--*"
        file_type: directory
      register: session_dir
      failed_when: session_dir.matched == 0

    - name: Verify tmux window was created
      ansible.builtin.command: tmux list-windows -t main -F "#{window_name}"
      register: tmux_windows
      changed_when: false
      failed_when: "'test-session' not in tmux_windows.stdout"

    - name: Clean up test session
      ansible.builtin.command: tmux kill-window -t main:test-session
      changed_when: true
      failed_when: false

    # =========================================================================
    # Summary
    # =========================================================================
    - name: Report optional component status
      ansible.builtin.debug:
        msg: |
          === OAuth Tokens ===
          Claude credentials: {{ 'present' if claude_creds.stat.exists else 'MISSING' }}
          Happy Coder tokens: {{ 'present' if happy_creds.stat.exists else 'not found (optional)' }}

          === Optional Components ===
          Tailscale: {{ 'installed' if tailscale_check.rc == 0 else 'not installed' }}
          Claude Code on host: {{ 'installed' if claude_host.rc == 0 and claude_host.stdout != '' else 'not installed' }}
          GitHub MCP: {{ 'configured' if github_mcp_exists.stdout is defined and 'github-mcp.service' in github_mcp_exists.stdout else 'not configured (no PAT)' }}
          GitHub MCP watchdog: {{ 'active' if watchdog_timer_active is defined and watchdog_timer_active.stdout == 'active' else 'not configured' }}
          Node.js version: {{ node_version.stdout | trim }}
          pnpm version: {{ pnpm_version.stdout | trim }}

    - name: All verifications passed
      ansible.builtin.debug:
        msg: "Deployment verified successfully!"
